AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para crear grupo de seguridad"
Resources:
  MySecurityGroup2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Grupo de seguridad creado desde la plantilla"
      GroupName: AppServerSecurityGroup2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  MyInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06aa3f7caf3a30282
      IamInstanceProfile: LabInstanceProfile
      InstanceType: t2.micro
      KeyName: vockey
      Tags:
        - Key: Name
          Value: AppServer_Prueba
      SecurityGroups:
        - !Ref MySecurityGroup2
      
        
          
          
            
     

     


